import { createSlice } from "@reduxjs/toolkit";
import { toast } from "react-toastify";

const initialState = {
  isLoadingCart: true,
  listCart: [],
  listCartFirst: [],
  totalProduct: "",
};

export const cartSlice = createSlice({
  name: "cart",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    displayCart: (state, action) => {
      state.listCart = action.payload;
      state.listCartFirst = action.payload;
      state.isLoadingCart = false;
      localStorage.setItem("listCart", JSON.stringify(action.payload));
    },
    doFetchListCartPending: (state) => {
      state.isLoadingCart = true;
    },

    doFetchListCartError: (state) => {
      state.isLoadingCart = false;
    },

    deleteProduct: (state, action) => {
      const newCart = state.listCart.filter((item) => {
        return item.productId._id !== action.payload;
      });
      state.listCart = newCart;
      toast.success("Đã xóa sản phẩm khỏi giỏ hàng", { toastId: "success1" });
      localStorage.setItem("listCart", JSON.stringify(newCart));
    },

    doLogoutCart: (state, action) => {
      state.isLoadingCart = false;
      state.listCart = [];
      state.listCartFirst = [];
      localStorage.removeItem("listCart");
    },

    addToCartService: (state, action) => {
      const itemIndex = state.listCart.findIndex(
        (item) => item.productId._id === action.payload._id
      );
      if (itemIndex < 0) {
        state.listCart.push({ productId: action.payload, quantity: 1 });
        toast.success("Đã thêm sản phẩm vào giỏ hàng", { toastId: "success1" });
        localStorage.setItem("listCart", JSON.stringify(state.listCart));
        // return;
      } else {
        toast.success("Sản phẩm đã có trong giỏ hàng", { toastId: "success1" });
        // localStorage.setItem("listCart", JSON.stringify(state.listCart));
        // return;
      }
    },

    increaseQuantity: (state, action) => {
      const itemIndex = state.listCart.findIndex(
        (item) => item.productId._id === action.payload
      );
      if (state.listCart[itemIndex].quantity === 10) {
        toast.success("Số lượng quá quy định", { toastId: "success1" });
        return;
      }

      state.listCart[itemIndex].quantity += 1;

      localStorage.setItem("listCart", JSON.stringify(state.listCart));
    },

    decreaseQuantity: (state, action) => {
      const itemIndex = state.listCart.findIndex(
        (item) => item.productId._id === action.payload
      );

      if (state.listCart[itemIndex].quantity > 1) {
        state.listCart[itemIndex].quantity -= 1;
      } else if (state.listCart[itemIndex].quantity === 1) {
        const newCart = state.listCart.filter((item) => {
          return item.productId._id !== action.payload;
        });
        state.listCart = newCart;
        toast.success("Đã xóa sản phẩm khỏi giỏ hàng", { toastId: "success1" });
      }

      localStorage.setItem("listCart", JSON.stringify(state.listCart));
    },

    deleteAllCart: (state, action) => {
      state.listCart = [];
      // state.listCartFirst = [];
      state.isLoadingCart = false;
      localStorage.setItem("listCart", JSON.stringify(state.listCart));
    },

    //CART FOR LOCAL STORAGE
  },

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const {
  doFetchListCartPending,
  displayCart,
  increaseQuantity,
  decreaseQuantity,
  deleteProduct,
  doLogoutCart,
  doFetchListCartError,
  addToCartService,
  deleteAllCart,
} = cartSlice.actions;

export default cartSlice.reducer;
