import { createSlice } from "@reduxjs/toolkit";
import { toast } from "react-toastify";

const initialState = {
  isLoadingCart: false,
  listCart: [],
  listCartFirst: [],
};

export const cartSlice = createSlice({
  name: "cart",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    doFetchListCartPending: (state) => {
      state.isLoadingCart = true;
    },

    doFetchListCartError: (state) => {
      state.isLoadingCart = false;
    },

    displayCart: (state, action) => {
      state.listCart = action.payload;
      state.listCartFirst = action.payload;
      state.isLoadingCart = false;
    },

    increaseQuantity: (state, action) => {
      const itemIndex = state.listCart.findIndex(
        (item) => item.productId._id === action.payload
      );
      state.listCart[itemIndex].quantity += 1;

      localStorage.setItem("listCart", JSON.stringify(state.listCart));
    },

    decreaseQuantity: (state, action) => {
      const itemIndex = state.listCart.findIndex(
        (item) => item.productId._id === action.payload
      );

      if (state.listCart[itemIndex].quantity > 1) {
        state.listCart[itemIndex].quantity -= 1;
      } else if (state.listCart[itemIndex].quantity === 1) {
        const newCart = state.listCart.filter((item) => {
          return item.productId._id !== action.payload;
        });
        state.listCart = newCart;
        toast.success("Đã xóa sản phẩm khỏi giỏ hàng", { toastId: "success1" });
      }

      localStorage.setItem("listCart", JSON.stringify(state.listCart));
    },

    deleteProduct: (state, action) => {
      const newCart = state.listCart.filter((item) => {
        return item.productId._id !== action.payload;
      });
      state.listCart = newCart;
      toast.success("Đã xóa sản phẩm khỏi giỏ hàng", { toastId: "success1" });
      localStorage.setItem("listCart", JSON.stringify(state.listCart));
    },

    doLogoutCart: (state, action) => {
      state.isLoadingCart = false;
      state.listCart = [];
      state.listCartFirst = [];
    },
  },

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const {
  doFetchListCartPending,
  displayCart,
  increaseQuantity,
  decreaseQuantity,
  deleteProduct,
  doActionChange,
  doLogoutCart,
  doFetchListCartError,
} = cartSlice.actions;

export default cartSlice.reducer;
