import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  isDisplayMenu: false,
  loading: true,
};

export const menuSlice = createSlice({
  name: "menu",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    displayMenu: (state, action) => {
      state.isDisplayMenu = true;
    },
    notDisplayMenu: (state, action) => {
      state.isDisplayMenu = false;
    },
    statusLoading: (state, action) => {
      state.loading = true;
    },
    statusNotLoading: (state, action) => {
      state.loading = false;
    },
  },

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const { displayMenu, notDisplayMenu, statusLoading, statusNotLoading } =
  menuSlice.actions;

export default menuSlice.reducer;
